version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adopet
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

# 📥 Para acessar o terminal do container:
# docker exec -it mysql_container bash

# 🐬 Dentro do container, para acessar o MySQL como root:
# mysql -u root -p
# (Senha: root)